apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic-app
  description: Petclinic App Website
  annotations:
    'backstage.io/kubernetes-label-selector': 'carto.run/workload-name=tanzu-spring-pet-clinic' 
spec:
  type: service
  lifecycle: experimental
  owner: spring-devs
  system: petclinic
